pipeline:
  - sources:
    - name: ocorrencias
      url: "https://servicos.dpf.gov.br/dadosabertos/SINARM_CSV/OCORRENCIAS/OCORRENCIAS_2024.csv"
    - name: portes
      url: "https://servicos.dpf.gov.br/dadosabertos/SINARM_CSV/PORTES/PORTES_2024.csv"
    - name: registros
      url: "https://servicos.dpf.gov.br/dadosabertos/SINARM_CSV/REGISTROS/REGISTROS_com_categoria_2024.csv"
